return {
	-- "lewis6991/spellsitter.nvim",
	-- config = function()
	-- 	require("spellsitter").setup({
	-- 		enable = true,
	-- 	})
	-- end,
	-- vim.keymap.set("n", "<leader>ts", function()
	-- 	vim.opt.spell = not vim.opt.spell:get()
	-- 	print("Spell-check " .. (vim.opt.spell:get() and "enabled" or "disabled"))
	-- end, { desc = "Toggle spell-checking" }),
	--
	-- vim.keymap.set("n", "<leader>en", function()
	-- 	vim.opt.spelllang = "en"
	-- 	print("Spell language set to English")
	-- end, { desc = "Set spell language to English" }),
	--
	-- vim.keymap.set("n", "<leader>pt", function()
	-- 	vim.opt.spelllang = "pt"
	-- 	print("Spell language set to Portuguese")
	-- end, { desc = "Set spell language to Portuguese" }),
}
